travis:
  secure:
    BINSTAR_TOKEN: XHtvWns8DLns9dKAELX3EMGjCyO7qX/05xl3mMOYuCQZ44St52J3Dz/JLo3WDh+mb1oAGvKM9f8Zh49WpsyM/T2f3Aysfe4xOOra0UWzSwU8FWzRFbOYd+YXBH1rQNA4VcykefyDaYJyF6IxjihmIawKgrqMTguH5UxyeHWkvKySQYmbHVSGPjfCHfV1DiBBpwFqOy1JZP9J78SxkJfl42OpnvjsmT2/B7pSgN4l7hIdTaR65aEezUa2dgX389TILOI9MJaD4cOjQL1kg6bpzhNjx7Qf1ImEdW1hvfbzqln8cheRMc4MzRE9Pyw8PMMhCbkhyhe8Q83ij4eNRvH6sDCKGmtjsF7LWUA9IXGPz7Y/y+AQiaw2IQqUG12f8nRmgM2RmNc+GHmFmYIXTa2vCTSo6VfCNBjWB1NAAsUr6tWJ/IE6wR9mFaVTLuZjUN5a1QB/NiycvB2hyiSXuZ9GhuiEzSy40Kzrr2N05t3UDdWzJiow+uUIWNgFwujA40SvZBBpIALgUF+wuVhbE4W+C1Kvck5D3cP6ebJiNEHRKFhtJsEGOyjSB1dbdKOs6x+vE/Fp6zdn8DHVp1sjM7iHugTEWvnPYHIFJ+7akjmVk6HFM/WBrSQIvLwQf7SLN4hP/78tB2MN755OZ2dm7ThrXLRiOLYmVW/Q/7MqyzeK5nQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
